### ISSUE TITLE
Organização

### ISSUE THREAD

**Issue by gentildpinto** [pangolano/hello-world#1]
Tá muito quieto aqui.
Nenhuma ideia de projecto para trabalharmos em conjunto?

**Comment by usandopythonjoao** [comment]
estamos a organizar as coisa

**Comment by joaroque** [comment]
@gentildpinto , nenhuma ideia?

**Comment by gentildpinto** [comment]
epha, até já tinha me esquecido dessa comunidade @joaroque kkkk

**Comment by gentildpinto** [comment]
o @codemesma está a quase um ano a organizar as coisas 😄

**Comment by joaroque** [comment]
Ahahahaha

Gentil D. Pinto ***@***.***> escreveu no dia quinta,
29/04/2021 à(s) 19:42:

**Comment by joaroque** [comment]
@gentildpinto, arranja algumas coisas aí para manter activa.

O @codemesma tem outro trabalho e ele largou o projecto

**Comment by gentildpinto** [comment]
@joaroque vou ver o que posso fazer mano 😅
